###
GET http://localhost:8080/hello/echo?message=Boksl

### 로또 번호 생성
GET http://localhost:8080/luck/lotto
Accept: application/json

### 로그인 요청
POST http://localhost:8080/api/login
Content-Type: application/json

{
    "username": "setvect",
    "password": "1234"
}

### health
GET http://localhost:8080/api/health

