
### 댓글 생성
POST http://localhost:8080/api/comments?module=BOARD&moduleId=10151
Authorization: {{authToken}}
Content-Type: application/json

{
    "content": "댓글 내용입니다."
}

### 댓글 수정
PUT http://localhost:8080/api/comments/10151
Authorization: {{authToken}}
Content-Type: application/json

{
    "content": "수정된 댓글 내용입니다.수정된 댓글 내용입니다.수정된 댓글 내용입니다.수정된 댓글 내용입니다.수정된 댓글 내용입니다."
}

### 댓글 삭제
DELETE http://localhost:8080/api/comments/10051
Authorization: {{authToken}}

### 댓글 목록 조회
GET http://localhost:8080/api/comments?module=BOARD&moduleId=10151&page=0&size=10
Authorization: {{authToken}}
