
### 메모 카테고리 생성
POST http://localhost:8080/api/memo-category
Authorization: {{authToken}}
Content-Type: application/json

{
    "name": "새로운 카테고리"
}

### 메모 카테고리 수정
PUT http://localhost:8080/api/memo-category/10001
Authorization: {{authToken}}
Content-Type: application/json

{
    "name": "수정된 카테고리 이름"
}

### 메모 카테고리 삭제
DELETE http://localhost:8080/api/memo-category/10000
Authorization: {{authToken}}

### 메모 카테고리 목록 조회
GET http://localhost:8080/api/memo-category
